# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

snmfl <- function(A, k, eta, alpha, max_iter, conv_delta, conv_interval) {
    .Call('snmfl_snmfl', PACKAGE = 'snmfl', A, k, eta, alpha, max_iter, conv_delta, conv_interval)
}

