all:
	$(MAKE) -C 09_SIS_diag_dsd
	$(MAKE) -C 10_SIS_surg_dsd
	$(MAKE) -C 11_SIS_recr_dsd
	$(MAKE) -C 12_SIS_diag_rec
	$(MAKE) -C 13_SIS_surg_rec
	$(MAKE) -C 15_SIS_NMF_combined
	$(MAKE) -C 16_SIS_NMF_alltogethernow
