.PHONY: all

all:
	$(MAKE) -C 18_SIS_diag_dsd_final
	$(MAKE) -C PCA_ICA_NMF_comparison

clean:
	$(MAKE) -C 18_SIS_diag_dsd_final clean
	$(MAKE) -C PCA_ICA_NMF_comparison clean

ultraclean:
	$(MAKE) -C 18_SIS_diag_dsd_final ultraclean
	$(MAKE) -C PCA_ICA_NMF_comparison ultraclean
